## NumPy Tutorial with Keith Galli

### 1. Import NumPy library

In [2]:
import numpy as np

### 2. The Basics

In [3]:
# Defining a 1D array in NumPy
a = np.array([1, 2, 3])
print(a)

array([1, 2, 3])

In [5]:
# Defining a 2D array in NumPy
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get dimension of the array
print(a.ndim, b.ndim)

1 2


In [8]:
# Get shape of the array (R, C)
print(a.shape, b.shape)

(3,) (2, 3)


In [10]:
# Get type of the array
print(a.dtype, b.dtype)

int32 float64


In [18]:
# Define fixed size for an array
a = np.array([1, 2, 3], dtype='int32')
a.dtype

dtype('int32')

In [19]:
# Get size of the array
print(a.itemsize, b.itemsize)

4 8


In [20]:
# Get total size of the array
print(a.nbytes, b.nbytes)

# Calculate total size of the array
a_itemsize = a.size * a.itemsize
print(a_itemsize)

12 48
12


### 3. Accessing/Changing specific elements, rows, columns, etc.

In [24]:
# Define array a
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
# Get a specific element [R, C]
a[1, 5]

13

In [28]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
# Get a specific column
a[:, 3]

array([ 4, 11])

In [34]:
# Slicing [start:stop:step]
a[0, 1:6:2]

array([2, 4, 6])

In [41]:
# Changing a certain element in the array
a[0, 6] = 8
print(a)

# Changing 2 elements in the array
a[:, 3] = [20, 30]
print(a)

[[ 1  2  3  4  5  6  8]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3 20  5  6  8]
 [ 8  9 10 30 12 13 14]]


#### 3D Example:

In [43]:
# Defining a 3D array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
# Get specific element (work outside in) [set, row, column]
b[0, 1, :]

array([3, 4])

In [47]:
# Replace values
b[:, 1, :] = [[1, 1], [2, 2]]
print(b)

[[[1 2]
  [1 1]]

 [[5 6]
  [2 2]]]


#### Documentation for Indexing: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

### 4. Initializing different types of arrays

In [53]:
# Create an all 0s matrix
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# Create an all 1s matrix
np.ones((2, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [54]:
# Create a matrix with any other number
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [55]:
# Create a matrix with given shape (full_like)
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [58]:
# Create a matrix of random decimal numbers
np.random.rand(3, 3)

# Create a matrix of random decimal numbers given shape
np.random.random_sample(a.shape)

array([[0.94893765, 0.77815148, 0.19109479, 0.01547315, 0.71096989,
        0.76549772, 0.16415928],
       [0.79452171, 0.45755963, 0.55473112, 0.86063407, 0.19808943,
        0.34031908, 0.85765561]])

In [67]:
# Create a matrix of random integer values (start[default=0], end[exclusive], size)
np.random.randint(0, 2, size=(3,3))

array([[1, 0, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [70]:
# Create identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
# Repeat values of an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Produce a certain array:

In [77]:
o = np.ones((5,5))
print(o)

z = np.zeros((3,3))
z[1, 1] = 9
print(z)

o[1:4, 1:4] = z
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!

In [79]:
x = np.array([1, 2, 3])
y = x.copy() # Produce a copy of x
y[0] = 100

print(x) # Also had value of 100 at index 0
print(y)

[1 2 3]
[100   2   3]


#### Documentation for Array Creation: https://numpy.org/doc/stable/reference/routines.array-creation.html

### 5. Mathematics

In [85]:
# Define array a
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [87]:
# Addition
a + 2

array([3, 4, 5, 6])

In [82]:
# Subtraction
a - 2

array([-1,  0,  1,  2])

In [83]:
# Multiplication
a * 2

array([2, 4, 6, 8])

In [86]:
# Division
a / 2

array([0.5, 1. , 1.5, 2. ])

In [88]:
# Addition of 2 arrays
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [89]:
# Exponents
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [92]:
# Trigonometry
print(a)
print(np.sin(a))
print(np.cos(a))

[1 2 3 4]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


#### Documentation for Math Routines: https://numpy.org/doc/stable/reference/routines.math.html

### 6. Linear Algebra

In [96]:
# Multiply 2 matrices
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [98]:
# Find the determinant of a matrix
c = np.identity(3)
print(c)

np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#### Documentation for Linear Algebra: https://numpy.org/doc/stable/reference/routines.linalg.html

### 7. Statistics

In [99]:
# Define array
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
# Minimum value
print(np.min(stats))

# Minimum value at each row
print(np.min(stats, axis=1))

# Minimum value at each column
print(np.min(stats, axis=0))

1
[1 4]
[1 2 3]


In [101]:
# Maximum value
np.max(stats)

6

In [105]:
# Summation of all values in the matrix
np.sum(stats)

21

### 8. Reorganizing Arrays

In [107]:
# Define before array
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

# Reshape before array (should be same size)
after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [109]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### 9. Miscellaneous

#### Loading data from file

In [114]:
data = np.genfromtxt('data.txt', delimiter=',')

# Change data type (makes a copy)
data.astype('int32')

# Makes permanent change
data = data.astype('int32')
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Advanced Indexing

In [117]:
# Find data given condition (True/False)
data > 50

# Find values of data given condition
data[data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [118]:
# Indexing with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [119]:
# Finding if any data in an axis satisfies given condition
np.any(data > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [120]:
# Finding if all data in an axis satisfies given condition
np.all(data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [121]:
# Multiple conditions
(data > 50) & (data < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [154]:
# Indexing exercise
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])

print(x[2:4, 0:2])
print(x[[0, 1, 2, 3], [1, 2, 3, 4]])
print(x[[0, 4, 5], 3:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
